"""
Domain models for portfolio, market data, risk, optimization, and rebalancing.
"""
from dataclasses import dataclass, field
from typing import List, Dict, Optional
import pandas as pd


@dataclass
class Holding:
    """Represents a single position in the portfolio."""
    ticker: str
    quantity: float = 0.0
    target_weight: float = 0.0
    min_weight: float = 0.0
    max_weight: float = 1.0
    current_price: float = 0.0
    market_value: float = 0.0
    current_weight: float = 0.0


@dataclass
class RiskConfig:
    """Parameters governing risk analytics and Value at Risk."""
    confidence_level: float = 0.95
    var_horizon_days: int = 1
    lookback_days: int = 756  # ~3 years of trading days


@dataclass
class RebalanceConfig:
    """Parameters governing allocation drift and trade generation."""
    drift_threshold: float = 0.05  # 5% drift threshold
    minimum_trade_value: float = 1000.0
    transaction_cost_rate: float = 0.0010  # 10 bps default


@dataclass
class PortfolioConfig:
    """Complete portfolio configuration."""
    name: str = "Balanced Growth"
    initial_capital: float = 1_000_000.0
    base_currency: str = "USD"
    benchmark: str = "SPY"
    holdings: List[Holding] = field(default_factory=list)
    risk_config: RiskConfig = field(default_factory=RiskConfig)
    rebalance_config: RebalanceConfig = field(default_factory=RebalanceConfig)


@dataclass
class MarketData:
    """Normalized price and return matrices from market data providers."""
    prices: pd.DataFrame
    returns: pd.DataFrame
    benchmark_prices: pd.Series
    benchmark_returns: pd.Series
    start_date: str
    end_date: str
    source: str = "yfinance"
    is_demo: bool = False
    data_quality_warnings: List[str] = field(default_factory=list)


@dataclass
class OptimizationConstraints:
    """Constraints applied during portfolio optimization."""
    min_weight: float = 0.0
    max_weight: float = 1.0
    allow_short: bool = False
    target_return: Optional[float] = None
    custom_bounds: Optional[Dict[str, tuple[float, float]]] = None


@dataclass
class OptimizationResult:
    """Result of a SciPy optimization run."""
    weights: Dict[str, float]
    expected_return: float
    volatility: float
    sharpe: float
    success: bool
    status_message: str
    iterations: int = 0


@dataclass
class TradeRecommendation:
    """Actionable trade recommendation generated by rebalancing engine."""
    ticker: str
    current_weight: float
    target_weight: float
    drift: float
    current_value: float
    target_value: float
    trade_value: float
    action: str  # BUY, SELL, HOLD
    priority: int
    current_price: float
    estimated_shares: int
    reason: str
